# Generated by Django 2.2.1 on 2019-05-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookcontent',
            old_name='type',
            new_name='book',
        ),
    ]
